[package]

name = "unicase"
version = "0.0.4"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
description = "A case-insensitive wrapper around strings."
repository = "https://github.com/seanmonstar/unicase"
license = "MIT"
keywords = ["lowercase", "case", "case-insensitive"]
